#!/bin/bash

# This is a thin wrapper around kpcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using kpcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_KPCOIND

# Grab the value of $REAL_KPCOINCLI which may be kpcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_KPCOINCLI}" "$@" | sed 's/\r//'
